# Generated by Django 3.1.4 on 2021-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20210516_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='priceMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ids', models.IntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
