# Generated by Django 3.1.4 on 2021-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('trailer', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='main-slide')),
            ],
        ),
    ]
