# Generated by Django 3.1.4 on 2021-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('trailer', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('image', models.ImageField(upload_to='new-releases')),
            ],
        ),
    ]
